apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

secretGenerator:
  - name: hono-api-secret
    literals:
      - DATABASE_URL=postgres://postgres:postgres@postgres-service:5432/postgres
  - name: postgres-credentials
    literals:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../base
  - configmap.yaml
