apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

secretGenerator:
  - name: hono-api-secret
    literals:
      - DATABASE_URL=postgres://postgres:postgres@postgres-service:5432/postgres


generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../base
